//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OJTManagerNew.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CompanyInTerm
    {
        public int ID { get; set; }
        public Nullable<int> CompanyID { get; set; }
        public Nullable<int> TermID { get; set; }
    
        public virtual Company Company { get; set; }
        public virtual Term Term { get; set; }
    }
}
