//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OJTManagerNew.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Job
    {
        public int JobID { get; set; }
        public string JobName { get; set; }
        public string MajorID { get; set; }
        public int CompanyID { get; set; }
        public string JobDescription { get; set; }
        public System.DateTime OpenDate { get; set; }
        public System.DateTime CloseDate { get; set; }
        public int StudentQuantity { get; set; }
        public int Status { get; set; }
    
        public virtual Company Company { get; set; }
        public virtual Major Major { get; set; }
    }
}
