//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OJTManager.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class History
    {
        public int ID { get; set; }
        public string StudentID { get; set; }
        public int CompanyID { get; set; }
        public int TermID { get; set; }
        public int Status { get; set; }
    
        public virtual Company Company { get; set; }
        public virtual Student Student { get; set; }
        public virtual Term Term { get; set; }
    }
}
